# Generated by Django 3.2.6 on 2021-09-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210901_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('R', 'Rental'), ('S', 'Sale')], max_length=1, null=True),
        ),
    ]
